version: "3"
services:
  db:
    image: postgres
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  db-dev:
    image: postgres
    volumes:
      - ${DB_PATH_DEV}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_DEV}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
