version: "3"
services:
  db:
    image: postgres
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  db-dev:
    image: postgres
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_DEV}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  web:
    build: .
    command: gunicorn ecommerce.wsgi --bind 0.0.0.0:${PORT}
    volumes:
      - .:/code
    environment:
      - DB_HOST=${HOST_FROM_DOCKER}
      - DJANGO_DEBUG=False
    ports:
      - 8000:${PORT}
    depends_on:
      - db
