# Generated by Django 4.0.6 on 2022-10-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_address_options_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='authentication_provider',
        ),
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client'),
        ),
    ]
