# Generated by Django 4.0.6 on 2022-10-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_authentication_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
