# Generated by Django 4.0.6 on 2022-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_line',
            field=models.CharField(help_text='Sector, Street', max_length=100, verbose_name='first line'),
        ),
        migrations.AlterField(
            model_name='address',
            name='second_line',
            field=models.CharField(help_text='Building, Apartment, Floor, House No.', max_length=100, verbose_name='second line'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=40, verbose_name='state'),
        ),
    ]
