# Generated by Django 4.0.6 on 2022-09-06 01:42

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=60)),
                ('icon', thumbnails.fields.ImageField(upload_to='slide/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
