# Generated by Django 4.0.6 on 2022-09-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slideimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideimage',
            old_name='icon',
            new_name='image',
        ),
    ]
