# Generated by Django 4.0.6 on 2022-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
