# Generated by Django 4.0.6 on 2022-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_slideimage_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='order',
            field=models.PositiveIntegerField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
