# Generated by Django 4.0.6 on 2022-11-05 17:51

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slideimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideimage',
            options={'verbose_name': 'Slide Image', 'verbose_name_plural': 'Slide Images'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='image',
            field=thumbnails.fields.ImageField(upload_to='slide/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='order',
            field=models.PositiveIntegerField(unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='show',
            field=models.BooleanField(default=False, verbose_name='show'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='text',
            field=models.CharField(max_length=60, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone'),
        ),
    ]
