# Generated by Django 4.0.6 on 2022-09-12 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cookie_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', True), ('cookie_id__isnull', True), _connector='OR'), models.Q(('user__isnull', True), ('cookie_id__isnull', True), _negated=True)), name='user_or_cookieid_null'),
        ),
    ]
