# Generated by Django 4.0.6 on 2022-09-20 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_cookie_id_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
