# Generated by Django 4.0.6 on 2022-10-03 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartproducts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
