# Generated by Django 4.0.6 on 2022-10-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartproducts_final_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartproducts',
            name='product_card_unique_constraint',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='final_price',
        ),
        migrations.AddConstraint(
            model_name='cartproducts',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='product_cart_unique_constraint'),
        ),
    ]
