# Generated by Django 4.0.6 on 2022-10-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_orderproducts_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash on delivery'), ('Card', 'Card on delivery'), ('Transfer', 'Bank Transfer on delivery'), ('Pickup', 'Payment on pick up')], default='Cash', max_length=8),
            preserve_default=False,
        ),
    ]
