# Generated by Django 4.0.6 on 2022-10-21 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_order_completed_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_to_manage', to=settings.AUTH_USER_MODEL),
        ),
    ]
