# Generated by Django 4.0.6 on 2022-10-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_client_alter_order_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
