# Generated by Django 4.0.6 on 2022-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=44, max_digits=12),
            preserve_default=False,
        ),
    ]
