# Generated by Django 4.0.6 on 2022-10-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
    ]
