# Generated by Django 4.0.6 on 2022-11-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_price_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'Order Products', 'verbose_name_plural': 'Order Products'},
        ),
    ]
