contact-info:
  address: "123 Street, New York, USA"
  mail: "info@example.com"
  phone: "+012 345 67890"
  rights: "2022 Company. All Rights Reserved."
  instagram: "https://instagram.com"
  facebook: "https://facebook.com"
