# Generated by Django 4.0.6 on 2022-07-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_imageproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='name',
        ),
    ]
