# Generated by Django 4.0.6 on 2022-07-18 01:42

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_imageproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=thumbnails.fields.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='products.product'),
        ),
    ]
