# Generated by Django 4.0.6 on 2022-07-18 02:36

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_imageproduct_image_alter_imageproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=thumbnails.fields.ImageField(default='a', upload_to='category/'),
            preserve_default=False,
        ),
    ]
