# Generated by Django 4.0.6 on 2022-07-21 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='category/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
