# Generated by Django 4.0.6 on 2022-07-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='icon',
        ),
    ]
