# Generated by Django 4.0.6 on 2022-08-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_name_en_us_category_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
