# Generated by Django 4.0.6 on 2022-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_extradataproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradataproduct',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='extradataproduct',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
