# Generated by Django 4.0.6 on 2022-08-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_extradataproduct_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='general_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en_us',
            new_name='general_description_en_us',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_es',
            new_name='general_description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_description',
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='products.product')),
            ],
        ),
        migrations.AlterField(
            model_name='extradataproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='products.typeproduct'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='products.typeproduct'),
        ),
    ]
