# Generated by Django 4.0.6 on 2022-08-16 17:16

import django.db.models.deletion
import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_typeproduct_description_en_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', thumbnails.fields.ImageField(upload_to='products/configurations/')),
            ],
        ),
        migrations.RenameModel(
            old_name='ExtraDataProduct',
            new_name='ProductExtraData',
        ),
        migrations.AddField(
            model_name='product',
            name='general_image',
            field=thumbnails.fields.ImageField(default=1, upload_to='products/general/'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='TypeProduct',
            new_name='ProductConfiguration',
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='products.productconfiguration'),
        ),
    ]
