# Generated by Django 4.0.6 on 2022-08-16 18:11

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', thumbnails.fields.ImageField(upload_to='products/general/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='general_image',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='picture',
            field=thumbnails.fields.ImageField(default='a', upload_to='products/configuration/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='products.product'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='products.product'),
        ),
    ]
