# Generated by Django 4.0.6 on 2022-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productpicture_remove_product_general_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
