# Generated by Django 4.0.6 on 2022-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productconfiguration_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name_en_us',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name_es',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
