# Generated by Django 4.0.6 on 2022-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_name_alter_product_name_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name_es',
            field=models.TextField(null=True),
        ),
    ]
