# Generated by Django 4.0.6 on 2022-08-19 22:08

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_name_alter_product_name_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=thumbnails.fields.ImageField(upload_to='category/'),
        ),
    ]
