# Generated by Django 4.0.6 on 2022-08-27 01:18

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_productconfiguration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfiguration',
            name='picture',
            field=thumbnails.fields.ImageField(upload_to='products/configurations/'),
        ),
    ]
