# Generated by Django 4.0.6 on 2022-11-05 17:51

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productconfiguration_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productconfiguration',
            options={'verbose_name': 'Product Configuration', 'verbose_name_plural': 'Product Configurations'},
        ),
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name': 'Product Picture', 'verbose_name_plural': 'Product Pictures'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=thumbnails.fields.ImageField(upload_to='category/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='general_description',
            field=models.TextField(blank=True, verbose_name='general description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='general_description_en_us',
            field=models.TextField(blank=True, null=True, verbose_name='general description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='general_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='general description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_us',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='current price'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='description_en_us',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name_en_us',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='name_es',
            field=models.TextField(null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='picture',
            field=thumbnails.fields.ImageField(upload_to='products/configurations/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='picture',
            field=thumbnails.fields.ImageField(upload_to='products/general/', verbose_name='picture'),
        ),
    ]
