# Generated by Django 4.0.6 on 2022-12-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='store_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='store id'),
        ),
    ]
